/// An instance of the kitbasher engine.
pub struct KBEngine {}

impl KBEngine {
    /// Creates a new instance of the engine.
    pub fn new(_parts: &[PartData]) -> Self {
        Self {}
    }

    /// Returns the set of valid next placements.
    pub fn gen_candidates(&self) -> Vec<PlacedConfig> {
        todo!()
    }

    /// Places a part on the model.
    ///
    /// This doesn't check whether the config is valid, only use configs generated by `gen_candidates`.
    pub fn place_part(&mut self, _placement: &PlacedConfig) {}

    /// Returns the current model.
    pub fn get_model(&self) -> Vec<PlacedConfig> {
        todo!()
    }

    /// Clears the current model.
    pub fn clear_model(&mut self) {}
}

/// Basic data for a part.
pub struct PartData {}

/// A part's configuration after being placed.
pub struct PlacedConfig {}
